import os
import torch
import torch.nn as nn

from .hash.hash import HashLayer
from ..base import BaseModel
from common.register import registry
from .loss import HyP, MagnaProxyLoss, KentProxyLoss
import numpy as np
from scipy.optimize import linear_sum_assignment
import math
import xlrd

def rand_unit_rect(npoints, ndim):
    '''
    Generates "npoints" number of vectors of size "ndim"
    such that each vectors is a point on an "ndim" dimensional sphere
    that is, so that each vector is of distance 1 from the center
    npoints -- number of feature vectors to generate
    ndim -- how many features per vector
    returns -- np array of shape (npoints, ndim), dtype=float64
    '''
    vec = np.random.randint(0, 2, size=(npoints, ndim))
    vec[vec==0] = -1
    return vec


def gene_noise(embeedings, noises):
    data_size = embeedings.shape[0]
    assgined_noise = dict(zip(range(data_size), noises))
    # do forward pass on batch - features
    losses = np.empty(shape=(data_size, data_size), dtype='float64')

    # calculate l2 loss between all...
    # noises randomly assigned and features generated by the network
    for i in range(data_size):
        fts = np.repeat(np.expand_dims(embeedings[i], axis=0), data_size, axis=0)
        l2 = np.linalg.norm(fts - noises, axis=1)
        losses[i] = l2

    # rearrange noises such that the total loss is minimal (hungarian algorithm)
    row_ind, col_ind = linear_sum_assignment(losses)
    for r, c in zip(row_ind, col_ind):
        assgined_noise[r] = noises[c]

    # get the same noises as before but in new assignment order
    new_noise = np.empty(shape=noises.shape, dtype='float64')
    for i in range(data_size):
        new_noise[i] = assgined_noise[i]
    return new_noise


@registry.register_model("KDPH")
class KDPH(BaseModel):

    DEFAULT_CONFIG_FILE = {"base": "confing/DCMHT/base.yaml"}

    def __init__(self, 
                cfg,
                outputDim: int=16, 
                clipPath: str="./ViT-B-32.pt",
                train_num: int=10000,
                numclass: int=80,
                hypseed: int=1,
                alpha: float=0,
                beta: float=0,
                lambda_cm: float=0,
                base_margin: float=0.3,
                gamma: float=0.1,
                tau: float=0.1,
                noise:float=0.1):
        super().__init__()
        # assert os.path.isfile(clipPath), f"{clipPath} is not exist!"
        self.cfg = cfg
        self.noise = noise
        embed_dim, self.backbone = self.load_backbone(clipPath=clipPath, return_patches=False)
        self.hash = HashLayer(inputDim=embed_dim, outputDim=outputDim)
        self.output_dim = outputDim
        pwd = os.path.dirname(os.path.realpath(__file__))
        sheet = xlrd.open_workbook(os.path.join(pwd, 'loss/codetable.xlsx')).sheet_by_index(0)
        threshold = sheet.row(outputDim)[math.ceil(math.log(numclass, 2))].value

        self.hyp = KentProxyLoss(numclass=numclass, output_dim=outputDim, threshold=threshold, alpha=alpha, lambda_cm=lambda_cm, base_margin=base_margin, gamma=gamma, tau=tau)

    def encode_image(self, image):

        image_embed = self.backbone.encode_image(image)
        image_embed = self.hash.encode_img(image_embed)

        return image_embed

    def encode_text(self, text):
        text_embed = self.backbone.encode_text(text)
        text_embed = self.hash.encode_txt(text_embed)

        return text_embed
    
    @classmethod
    def from_config(cls, cfg, output_dim=16, train_num=10000):
        clip_path = cfg.get("clip_path", "./ViT-B-32.pt")
        numclass = cfg.get("numclass", 80)
        base_margin=cfg.get("base_margin", 0.3)
        hypseed = cfg.get("hypseed", 0)
        alpha = cfg.get("alpha", 0.8)
        beta = cfg.get("beta", 0.1)
        lambda_cm = cfg.get("lambda_cm", 10)
        tau = cfg.get("tau", 0.1)
        gamma = cfg.get("gamma", 0.2)
        noise = cfg.get("noise", 0.1)

        print(cfg)
        model = cls(
            cfg=cfg, 
            outputDim=output_dim, 
            clipPath=clip_path, 
            train_num=train_num,
            numclass=numclass,
            hypseed=hypseed,
            alpha=alpha,
            beta=beta,
            lambda_cm=lambda_cm,
            base_margin=base_margin,
            gamma=gamma,
            tau=tau,
            noise=noise
        )
        return model
    
    def loss(self, image, text, labels=None, indexs=None, **kwags):
        device = image.device
        batch_size_, code_length = image.shape
        s_vector = rand_unit_rect(batch_size_, code_length)

        i_noises = gene_noise(image.cpu().detach().numpy(), s_vector)
        t_noises = gene_noise(text.cpu().detach().numpy(), s_vector)

        i_noises = torch.from_numpy(i_noises).float().to(device)
        t_noises = torch.from_numpy(t_noises).float().to(device)
        i_noise_loss = image.mul(i_noises).sum(dim=-1).mean()
        t_noise_loss = text.mul(t_noises).sum(dim=-1).mean()
        noise_loss = i_noise_loss + t_noise_loss
        
        loss1, hyp_loss_dict  = self.hyp(image, text, labels)
        loss = loss1 - self.noise * noise_loss
        loss_dict = {
            "All loss": loss1.data,
            "Noise loss": noise_loss.data,
            **hyp_loss_dict
            }

        return loss, loss_dict

    def object_function(self, img_hash, txt_hash, labels=None, indexs=None, **kwags):
        if labels is None:
            labels = torch.ones([img_hash.shape[0]], dtype=torch.int)
            labels = labels.diag()
        return self.loss(img_hash, txt_hash, labels, indexs, **kwags)

